### ISSUE TITLE
Getting unexpected token '<' vue error

### ISSUE THREAD

**Issue by egornmore** [akahon/vue-sidebar-menu-akahon#4]
Hello, I'm getting an unexpected token '<' vue error, any ideas why it's happening? That error occurs only after rebuilding the project, after disabling and enabling the sidebar it works. Does [vue-sidebar-menu-akahon] has to be in the node_modules root folder?

**Comment by egornmore** [comment]
Renamed component so that there are no hyphens e.g SidebarMenu, placed it to components folder in root, removed `import VueSidebarMenuAkahon from "vue-sidebar-menu-akahon";` now it works

**Comment by akahon** [comment]
Hi, thanks for your attention. I apologize for not responding in time. If you use the command below, such errors will not occur 

`npm install --save vue-sidebar-menu-akahon`
