### ISSUE TITLE
Can I use this with Inertia and Laravel?

### ISSUE THREAD

**Issue by andrewdwallo** [akahon/vue-sidebar-menu-akahon#9]

**Comment by andrewdwallo** [comment]
It works with Inertia but I noticed that the loading of a page is extremely long compared to the usual amount of time... why is this?

**Comment by akahon** [comment]
Sorry for not being able to respond immediately. I reduced the size of the component by 10 times and refactored the code a bit. Hopefully, it will load faster now. Please try again. I would appreciate it if you could describe the result.
